title: 'Walk the Talk with Michele Fiore & Brian Wilson'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9246931076049805
  brandStrength: 0.2591002485714853
  rhythmicContrast: 0.8893534617964178
  brandColors:
    - '#f6f1ed'
    - '#963019'
    - '#16174f'
    - '#667467'
    - '#afb1a9'
  lightness: 0.5878120826091617
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-71412409-1
  facebook: null
name: Walk the Talk
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1297872
layout_spectrum: 0.83132
