name: Walk the Talk
favicon: null
layout_spectrum: 0.83132
typography_spectrum: 0.5694764896761626
title: 'Walk the Talk with Michele Fiore & Brian Wilson'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71412409-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f1ed'
    - '#963019'
    - '#16174f'
    - '#667467'
    - '#afb1a9'
  brandStrength: 0.2591002485714853
  lightness: 0.5878120826091617
  saturation: 0.9246931076049805
  rhythmicContrast: 0.8893534617964178
purpose: []
